/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <section className='xl:pt-40 lg:pt-32 md:pt-24 pt-8'>
        <div className='max-w-7xl mx-auto px-4'>
          <div className='lg:mb-24 mb-8'>
            <h2 className='xl:text-6xl lg:text-4xl text-3xl font-bold text-white text-center'>
              METAVERSOL PASS
            </h2>
          </div>
          <div className="grid grid-cols-1 lg:gap-12 gap-4 items-center">
            <div>
              <div className='max-w-5xl w-full mx-auto text-center'>
                <p className='text-white lg:text-2xl md:text-xl text-md lg:mb-10 mb-6'>
                  The Expanse is intended to be a free-to-use platform, and no purchases will be required to log in and play with your friends.
                </p>
                <p className='text-white lg:text-2xl md:text-xl text-md lg:mb-10 mb-6'>
                  There will be a paid option in the form of a Metaversol Pass, this pass is not required, but does provide a number of benefits (none of which are designed to make a holder more powerful than a free-to-play player).
                </p>
                <p className='text-white lg:text-2xl md:text-xl text-md lg:mb-10 mb-6'>
                  The Pass will be available January, 2022 and the price is undetermined.
                </p>

                <div className='flex justify-center'>
                  <div className='btn-alpha-wrap relative'>
                    <div className='btn-alpha-blur'>

                    </div>
                    <button className="font-medium btn-alpha">
                      Learn More
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}
