/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'

export default function Services() {
    return (
        <div className='services-page'>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <section className='xl:pt-40 lg:pt-32 md:pt-24 pt-12 xl:pb-40 lg:pb-32 md:pb-60 pb-64 service-cta'>
                <div className='max-w-7xl mx-auto px-4'>
                    <div className="grid grid-cols-12 xl:gap-12 lg:gap-8 gap-4">
                        <div className="lg:col-span-5 col-span-12">
                            <h1 className='service-cta-title xl:text-6xl lg:text-6xl md:text-4xl text-4xl font-bold text-white lg:mb-40 mb-8'>
                                The Universe, In Your Hands
                            </h1>

                            <div className='btn-alpha-wrap relative'>
                                <div className='btn-alpha-blur'>
                                </div>
                            </div>

                            <div className='max-w-xl text-left w-full'>
                                <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-4 mb-2'>
                                    Every project that exists within The Expanse must purchase a basic onboarding package,
                                    and is guaranteed a number of special perks for their NFT holders, as well as a
                                    planet that will serve as a sort of headquarters for your project.
                                </p>
                            </div>
                        </div>
                        <div className="lg:col-span-7 col-span-12">
                            <div className='max-w-xl text-left w-full'>
                                <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-4 mb-4'>
                                    The Expanse is comprised entirely of the projects and businesses that we have brought onboard  our platform.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className='xl:pt-40 lg:pt-32 md:pt-24 pt-12'>
                <div className='max-w-7xl mx-auto px-4'>
                    <div className='flex md:flex-row flex-col lg:gap-16 gap-4 mb-10'>
                        <div style={{ flex: '6' }}>
                            <div className='flex md:text-left text-center justify-items-center md:flex-row flex-col lg:gap-8 gap-4'>
                                <div className='flex md:justify-start justify-center items-start'>
                                    <img className='object-none md:w-media-w-img-2 w-media-w-img-1 md:min-w-media-img-2 min-w-media-img-1' src='/assets/images/mediaIcon.png' alt=""></img>
                                </div>
                                <div>
                                    <h4 className='xl:text-2xl text-xl  text-purple font-bold md:mb-6 mb-3'>
                                        Access to all players in
                                        The Expanse
                                    </h4>
                                    <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-4 mb-6'>
                                        The Expanse is comprised entirely of the projects and businesses that we have brought onboard  our platform.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div style={{ flex: '6' }}>
                            <div className='flex md:text-left text-center justify-items-center md:flex-row flex-col lg:gap-8 gap-4'>
                                <div className='flex md:justify-start justify-center items-start'>
                                    <img className='object-none md:w-media-w-img-2 w-media-w-img-1 md:min-w-media-img-2 min-w-media-img-1' src='/assets/images/mediaIcon.png' alt=""></img>
                                </div>
                                <div>
                                    <h4 className='xl:text-2xl text-xl  text-purple font-bold md:mb-6 mb-3'>
                                        A planet designated specifically to your project, to be built out however you like
                                    </h4>
                                    <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-4 mb-6'>
                                        The Expanse is comprised entirely of the projects and businesses that we have brought onboard  our platform.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className='flex md:flex-row flex-col lg:gap-16 gap-4 mb-10'>
                        <div style={{ flex: '6' }}>
                            <div className='flex md:text-left text-center justify-items-center md:flex-row flex-col lg:gap-8 gap-4'>
                                <div className='flex md:justify-start justify-center items-start'>
                                    <img className='object-none md:w-media-w-img-2 w-media-w-img-1 md:min-w-media-img-2 min-w-media-img-1' src='/assets/images/mediaIcon.png' alt=""></img>
                                </div>
                                <div>
                                    <h4 className='xl:text-2xl text-xl  text-purple font-bold md:mb-6 mb-3'>
                                        A portal to your themed planet with your usage rules. Usage rules might include holder-only access, or other similar things
                                    </h4>
                                    <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-4 mb-6'>
                                        The Expanse is comprised entirely of the projects and businesses that we have brought onboard  our platform.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div style={{ flex: '6' }}>
                            <div className='flex md:text-left text-center justify-items-center md:flex-row flex-col lg:gap-8 gap-4'>
                                <div className='flex md:justify-start justify-center items-start'>
                                    <img className='object-none md:w-media-w-img-2 w-media-w-img-1 md:min-w-media-img-2 min-w-media-img-1' src='/assets/images/mediaIcon.png' alt=""></img>
                                </div>
                                <div>
                                    <h4 className='xl:text-2xl text-xl  text-purple font-bold md:mb-6 mb-3'>
                                        Tools to edit your
                                        project's planet
                                    </h4>
                                    <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-4 mb-6'>
                                        The Expanse is comprised entirely of the projects and businesses that we have brought onboard  our platform.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className='flex md:flex-row flex-col lg:gap-16 gap-4 mb-10'>
                        <div style={{ flex: '6' }}>
                            <div className='flex md:text-left text-center justify-items-center md:flex-row flex-col lg:gap-8 gap-4'>
                                <div className='flex md:justify-start justify-center items-start'>
                                    <img className='object-none md:w-media-w-img-2 w-media-w-img-1 md:min-w-media-img-2 min-w-media-img-1' src='/assets/images/mediaIcon.png' alt=""></img>
                                </div>
                                <div>
                                    <h4 className='xl:text-2xl text-xl  text-purple font-bold md:mb-6 mb-3'>
                                        In-verse sales platforms and promotional opportunities
                                    </h4>
                                    <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-4 mb-6'>
                                        The Expanse is comprised entirely of the projects and businesses that we have brought onboard  our platform.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div style={{ flex: '6' }}>
                            <div className='flex md:text-left text-center justify-items-center md:flex-row flex-col lg:gap-8 gap-4'>
                                <div className='flex md:justify-start justify-center items-start'>
                                    <img className='object-none md:w-media-w-img-2 w-media-w-img-1 md:min-w-media-img-2 min-w-media-img-1' src='/assets/images/mediaIcon.png' alt=""></img>
                                </div>
                                <div>
                                    <h4 className='xl:text-2xl text-xl  text-purple font-bold md:mb-6 mb-3'>
                                        Use your 3D NFTs as
                                        player avatars
                                    </h4>
                                    <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-4 mb-6'>
                                        The Expanse is comprised entirely of the projects and businesses that we have brought onboard  our platform.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className='flex md:flex-row flex-col lg:gap-16 gap-4 mb-10'>
                        <div style={{ flex: '6' }}>
                            <div className='flex md:text-left text-center justify-items-center md:flex-row flex-col lg:gap-8 gap-4'>
                                <div className='flex md:justify-start justify-center items-start'>
                                    <img className='object-none md:w-media-w-img-2 w-media-w-img-1 md:min-w-media-img-2 min-w-media-img-1' src='/assets/images/mediaIcon.png' alt=""></img>
                                </div>
                                <div>
                                    <h4 className='xl:text-2xl text-xl  text-purple font-bold md:mb-6 mb-3'>
                                        Special bonuses for holders of
                                        your NFT collection
                                    </h4>
                                    <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-4 mb-6'>
                                        The Expanse is comprised entirely of the projects and businesses that we have brought onboard  our platform.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div style={{ flex: '6' }}>

                        </div>
                    </div>
                    <div className='flex justify-center max-w-3xl mx-auto'>
                        <p className='text-blue-2 xl:text-xl lg:text-xl md:text-xl text-md lg:mb-10 mb-6 text-center'>
                            The cost of basic onboarding is 10% of your project`s mint, and may increase depending on  factors specific to your project.
                        </p>
                    </div>
                </div>
            </section>


            <section className='xl:pt-40 lg:pt-32 md:pt-24 pt-12'>
                <div className='max-w-7xl mx-auto px-4'>
                    <div className='lg:mb-24 mb-8'>
                        <h2 className='xl:text-5xl lg:text-4xl text-3xl font-bold text-white text-center'>
                            ADDITIONAL SERVICES
                        </h2>
                    </div>
                    <div className="grid grid-cols-1 lg:gap-12 gap-4 items-center">
                        <div>

                            <div className="grid grid-cols-1 lg:gap-12 gap-4 items-center">
                                <div>
                                    <div className='max-w-5xl w-full mx-auto text-center'>
                                        <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-10 mb-6'>
                                            The Expanse is intended to be a free-to-use platform, and no purchases will be required to log in and play with your friends.
                                        </p>
                                        <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-10 mb-6'>
                                            There will be a paid option in the form of a Metaversol Pass, this pass is not required, but does provide a number of benefits (none of which are designed to make a holder more powerful than a free-to-play player).
                                        </p>
                                        <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-10 mb-6'>
                                            The Pass will be available January, 2022 and the price is undetermined.
                                        </p>

                                        <div className='flex justify-center'>
                                            <div className='btn-alpha-wrap relative'>
                                                <div className='btn-alpha-blur'>

                                                </div>
                                                <button className="font-medium btn-alpha">
                                                    Learn More
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            
                        </div>
                    </div>
                </div>
            </section>

            <Footer />
        </div>
    )
}
